# Generated by Django 5.2.6 on 2026-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_can_manage_exhibitions_delete_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistprofile",
            name="avatar_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="artistprofile",
            name="instagram",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="artistprofile",
            name="twitter",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="artistprofile",
            name="website",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
