# Generated by Django 5.2.6 on 2026-08-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_artistprofile_avatar_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistprofile",
            name="facebook",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="linkedin",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="pinterest",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="tiktok",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="youtube",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
