# Generated by Django 5.2.6 on 2026-09-07 12:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_artistprofile_facebook_artistprofile_linkedin_and_more'),
        ('artworks', '0005_artwork_availability_status_artwork_copyright_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]+$', 'Use only letters, numbers, underscores, and hyphens.')]),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone', models.CharField(blank=True, default='', max_length=50)),
                ('inquiry_type', models.CharField(choices=[('acquisition', 'Acquisition / Purchase Inquiry'), ('exhibition', 'Exhibition Invitation'), ('general', 'General Inquiry')], default='general', max_length=32)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_inquiries', to=settings.AUTH_USER_MODEL)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='artworks.artwork')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
