# Generated by Django 5.2.6 on 2026-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
