# Generated by Django 5.2.6 on 2026-08-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionartwork',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_artworks', to='artworks.artwork'),
        ),
    ]
