# Generated by Django 5.2.6 on 2026-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exhibitions", "0002_alter_exhibitionartwork_artwork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibition",
            name="banner_image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
