# Generated by Django 5.2.6 on 2026-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="banner_image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="artworkimage",
            name="image_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
