# Generated by Django 5.2.6 on 2026-08-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0002_alter_artwork_banner_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artworkimage",
            name="is_process_image",
        ),
    ]
