# Generated by Django 5.2.6 on 2026-09-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_remove_artworkimage_is_process_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkversion',
            options={'ordering': ['-version_number']},
        ),
    ]
