# Generated by Django 5.2.6 on 2026-09-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_alter_artworkversion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='availability_status',
            field=models.CharField(choices=[('available_for_enquiry', 'Available for acquisition / enquiries'), ('not_for_sale', 'Not available for sale / Private collection'), ('on_loan', 'On loan'), ('sold', 'Acquired / Sold')], default='available_for_enquiry', max_length=30),
        ),
        migrations.AddField(
            model_name='artwork',
            name='copyright_holder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_artist_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='license_type',
            field=models.CharField(choices=[('all_rights_reserved', 'All Rights Reserved'), ('cc_by_nc_nd', 'Creative Commons BY-NC-ND'), ('cc_by_sa', 'Creative Commons BY-SA'), ('public_domain', 'Public Domain')], default='all_rights_reserved', max_length=50),
        ),
        migrations.AddField(
            model_name='artwork',
            name='provenance_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
