# Generated by Django 5.2.6 on 2026-09-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0007_artworkcontributor"),
    ]

    operations = [
        migrations.AddField(
            model_name="artworkcontributor",
            name="is_lead",
            field=models.BooleanField(default=False),
        ),
    ]
