# Generated by Django 5.2.6 on 2026-09-06 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_artworkview_source_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='artworkview',
            new_name='analytics_a_artwork_1a81bf_idx',
            old_name='analytics_a_artwork_8dce1e_idx',
        ),
        migrations.RenameIndex(
            model_name='artworkview',
            new_name='analytics_a_artwork_fb6737_idx',
            old_name='analytics_a_artwork_9c2ca9_idx',
        ),
        migrations.RenameIndex(
            model_name='artworkview',
            new_name='analytics_a_source_a41e14_idx',
            old_name='analytics_a_source_3f5d22_idx',
        ),
    ]
