# Generated by Django 5.2.6 on 2026-08-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='artwork',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='entity_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('artwork', 'Artwork'), ('exhibition', 'Exhibition')], default='', max_length=50),
        ),
    ]
