# Generated by Django 5.2.6 on 2026-08-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_remove_qrcode_artwork_qrcode_entity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_image_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
