# Generated by Django 5.2.6 on 2026-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr", "0003_qrcode_qr_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="qr_image_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
