import React from 'react'
import { Link } from 'react-router-dom'
import { ShieldCheck, Scale, FileText } from 'lucide-react'

export function TermsPage() {
  return (
    <div className="space-y-8 max-w-4xl mx-auto py-4">
      <div className="border-b border-white/[0.08] pb-6 space-y-2">
        <div className="flex items-center gap-2">
          <Scale className="h-5 w-5 text-indigo-400" />
          <span className="text-xs font-semibold uppercase tracking-wider text-indigo-400">Legal &amp; Governance</span>
        </div>
        <h1 className="text-3xl font-extrabold text-[#F4F4F5]">Terms of Service &amp; Content Ownership</h1>
        <p className="text-xs text-[#A1A1AA]">
          Last Updated: March 2026 · Governed in accordance with the laws of the Republic of Ghana.
        </p>
      </div>

      <div className="surface-card p-6 sm:p-8 space-y-6 text-xs sm:text-sm text-[#A1A1AA] leading-relaxed">
        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#F4F4F5]">1. Intellectual Property &amp; Artist Rights</h2>
          <p>
            LynqArt serves as a digital exhibition and artwork preservation platform. Artists retain 100% full intellectual property ownership and copyright of all uploaded physical artworks, Markdown artist statements, image graphics, and process documentation.
          </p>
          <p>
            By uploading content to LynqArt, artists grant the platform a non-exclusive license to host, render, and display the work to public visitors and exhibition attendees strictly for cultural, archiving, and preview purposes.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#F4F4F5]">2. Physical QR Code &amp; Access Terms</h2>
          <p>
            QR code tags generated by LynqArt link physical exhibition pieces to permanent digital URLs. Users may not tamper with or redirect LynqArt QR slugs to external malicious sources.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#F4F4F5]">3. AI Writing Assistant Guidelines</h2>
          <p>
            AI writing tools provided on LynqArt assist artists with statement drafting and grammar clarity. AI-generated drafts are never published automatically and require manual artist review and approval.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#F4F4F5]">4. Dispute Resolution &amp; Jurisdiction</h2>
          <p>
            These Terms shall be governed and construed in accordance with the laws of Ghana. Any disputes arising under these terms shall be subject to the jurisdiction of the courts of Ghana.
          </p>
        </section>
      </div>
    </div>
  )
}

export function PrivacyPage() {
  return (
    <div className="space-y-8 max-w-4xl mx-auto py-4">
      <div className="border-b border-white/[0.08] pb-6 space-y-2">
        <div className="flex items-center gap-2">
          <ShieldCheck className="h-5 w-5 text-indigo-400" />
          <span className="text-xs font-semibold uppercase tracking-wider text-indigo-400">Data Privacy Compliance</span>
        </div>
        <h1 className="text-3xl font-extrabold text-[#F4F4F5]">Privacy Policy</h1>
        <p className="text-xs text-[#A1A1AA]">
          Compliant with the Ghana Data Protection Act, 2012 (Act 843).
        </p>
      </div>

      <div className="surface-card p-6 sm:p-8 space-y-6 text-xs sm:text-sm text-[#A1A1AA] leading-relaxed">
        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#F4F4F5]">1. Data Controller &amp; Protection Principles</h2>
          <p>
            LynqArt is committed to protecting user personal data in compliance with the Data Protection Act, 2012 (Act 843) of Ghana. We process personal data lawfully, transparently, and only for specified exhibition management purposes.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#F4F4F5]">2. Anonymous Visitor Analytics</h2>
          <p>
            Public visitors scanning QR codes or viewing artwork pages are tracked using irreversible hashed identifiers to count unique visits without collecting or storing personally identifiable information (PII).
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-[#F4F4F5]">3. User Rights under Ghana Data Protection Act</h2>
          <p>
            Under Act 843, registered artists and users have the right to request access to, correction of, or deletion of their personal profile information at any time via the Profile Settings page or by contacting LynqArt administration.
          </p>
        </section>
      </div>
    </div>
  )
}
